### PR TITLE
Add hot reloading

### PR DESCRIPTION
**Pull request by deerob4**
In tandem with the PR for launcher, this PR adds support for hot-loading when developing the launcher.

Here we replace the normal call to `webpack` with one to `webpack-dev-server`.

The port is fixed to 8080. It would be nice to be able to pass this in as an environment variable, but the issue then is that there is no way for the `launcher.html` to know about this (since it is just a static file, not a template). We thus can't link to the correct file in the `script` tag.

### CODE REVIEW

**Comment by datenreisender** [comment]
Is the modified `webpack.config.js` here needed? As far as I understood we are only able to hot reload the launcher and the webpack configuration for that is separate in that project while the webpack configuration here is only used by the apps.

Would it be helpful for you, if we would not fix the port to 8080? I think we can make this work but I never had a need for it until now.

**Comment by deerob4** [comment]
Yes, the modified webpack config is needed. If the `react-refresh` dependency is not included, then apps throw an error when launched. It's a bit counterintuitive, but this solves the problem.

Which port do you mean? As I wrote above, I can't see that there's a way to avoid fixing the `webpack-dev-server` port.

**Comment by chunfantasy** [comment]
8080 is a very commonly used port. I advice not to make the port fixed to 8080.

**Comment by deerob4** [comment]
Good call, I changed it to 5004

**Comment by jonasem** [comment]
Might be impleneted in a different way by Pascal

**Pull request closed without merging**
